train:
  _target_: src.datasets.VoiceSpoofDataset
  path2dir: "data/LA/LA/ASVspoof2019_LA_train"
  path2dscr: "data/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trl.txt"
  part: "train"
  
val:
  _target_: src.datasets.VoiceSpoofDataset
  path2dir: "data/LA/LA/ASVspoof2019_LA_dev"
  path2dscr: "data/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt"
  part: "val"
test:
  _target_: src.datasets.VoiceSpoofDataset
  path2dir: "data/LA/LA/ASVspoof2019_LA_eval"
  path2dscr: "data/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt"
  part: "eval"
